### ISSUE TITLE
Adjust max width / right margin

### ISSUE THREAD

**Issue by ghost** [adobe/reactor-developer-docs#7]
Thoughts on changing 

```css
.sdldocs-components {
  flex: 1;
}
```
to
```css
.sdldocs-components {
  flex-grow: .9;
  flex-shrink: inherit;
  flex-basis: 0;
}
```
Or whatever you prefer to basically add padding-right [here in docs.css](https://github.com/Adobe-Marketing-Cloud/reactor-developer-docs/blob/e1ebbf5db8f285827c883bdb23c0cbd27a9c0d92/css/docs.css#L346-L348)
